name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create deployment zip
        run: zip -r deploy.zip . -x "*.git*"

      - name: Deploy
        uses: einaregilsson/beanstalk-deploy@v22

        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          application_name: house-price-predictor
          environment_name: House-price-predictor-env
          region: eu-north-1

          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
